import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const sidebar = readFileSync(new URL('./components/Sidebar.tsx', import.meta.url), 'utf8')
const appTitleBar = readFileSync(new URL('./components/AppTitleBar.tsx', import.meta.url), 'utf8')
const composer = readFileSync(new URL('./components/ChatBox.tsx', import.meta.url), 'utf8')
const productGuide = readFileSync(new URL('./components/ProductGuide.tsx', import.meta.url), 'utf8')
const onboarding = readFileSync(new URL('./components/OnboardingDialog.tsx', import.meta.url), 'utf8')
const app = readFileSync(new URL('./App.tsx', import.meta.url), 'utf8')
const i18n = readFileSync(new URL('./i18n.tsx', import.meta.url), 'utf8')
const knowledge = readFileSync(new URL('./components/KnowledgeBasePage.tsx', import.meta.url), 'utf8')
const knowledgePage = readFileSync(new URL('./components/KnowledgePage.tsx', import.meta.url), 'utf8')
const settings = readFileSync(new URL('./components/SettingsPage.tsx', import.meta.url), 'utf8')
const settingsSchema = readFileSync(new URL('./settings.ts', import.meta.url), 'utf8')
const websocket = readFileSync(new URL('./hooks/useWebSocket.ts', import.meta.url), 'utf8')
const memory = readFileSync(new URL('./components/UserMemoryPage.tsx', import.meta.url), 'utf8')
const notebook = readFileSync(new URL('./components/NotesPage.tsx', import.meta.url), 'utf8')
const notebookLiveEditor = readFileSync(new URL('./components/NotebookLiveEditor.tsx', import.meta.url), 'utf8')
const desktopBehavior = readFileSync(new URL('./desktop.ts', import.meta.url), 'utf8')
const backendMain = readFileSync(new URL('../../crates/tutor-web/src/main.rs', import.meta.url), 'utf8')
const backendRoutes = readFileSync(new URL('../../crates/tutor-web/src/routes/mod.rs', import.meta.url), 'utf8')
const notebookRoutes = readFileSync(new URL('../../crates/tutor-web/src/routes/notebook.rs', import.meta.url), 'utf8')
const knowledgeRoutes = readFileSync(new URL('../../crates/tutor-web/src/routes/knowledge.rs', import.meta.url), 'utf8')
const websocketRoutes = readFileSync(new URL('../../crates/tutor-web/src/routes/ws.rs', import.meta.url), 'utf8')
const memoryStore = readFileSync(new URL('../../crates/tutor-web/src/memory_store.rs', import.meta.url), 'utf8')
const memoryRoutes = readFileSync(new URL('../../crates/tutor-web/src/routes/memory.rs', import.meta.url), 'utf8')
const agentCapability = readFileSync(new URL('../../crates/tutor-agent/src/capability.rs', import.meta.url), 'utf8')
const agentLibrary = readFileSync(new URL('../../crates/tutor-agent/src/lib.rs', import.meta.url), 'utf8')
const tauriConfig = readFileSync(new URL('../../src-tauri/tauri.conf.json', import.meta.url), 'utf8')
const desktopCapabilities = readFileSync(new URL('../../src-tauri/capabilities/default.json', import.meta.url), 'utf8')

test('primary navigation exposes intent-oriented Sources, Notebook, and Personalization labels', () => {
  assert.match(sidebar, /export type AppView = 'assistant' \| 'knowledge' \| 'notebook' \| 'memory' \| 'settings'/)
  assert.match(sidebar, /key: 'assistant'/)
  assert.match(sidebar, /key: 'knowledge'/)
  assert.match(sidebar, /key: 'notebook'/)
  assert.match(sidebar, /key: 'memory'/)
  assert.doesNotMatch(sidebar, /key: '(tutor|space)'/)
  assert.match(i18n, /'nav\.knowledge': '资料'/)
  assert.match(i18n, /'nav\.memory': '个性化'/)
  assert.match(i18n, /'nav\.knowledge': 'Sources'/)
  assert.match(i18n, /'nav\.memory': 'Personalization'/)
  assert.doesNotMatch(i18n, /'nav\.knowledge': '知识库'/)
  assert.doesNotMatch(i18n, /'nav\.memory': '记忆'/)
})

test('sidebar control lives in a fixed custom window frame above compact branding', () => {
  assert.match(appTitleBar, /data-app-titlebar="true"/)
  assert.match(appTitleBar, /app-titlebar-sidebar-toggle absolute left-3/)
  assert.match(appTitleBar, /app-titlebar-sidebar-toggle[\s\S]*?h-8 w-10/)
  assert.match(appTitleBar, /data-tauri-drag-region/)
  assert.match(appTitleBar, /data-window-controls="true"/)
  assert.match(appTitleBar, /sidebarCollapsed \? <PanelLeftOpen size=\{18\} \/> : <PanelLeftClose size=\{18\} \/>/)
  assert.match(sidebar, /data-sidebar-brand="true"/)
  assert.match(sidebar, /overflow-hidden border-r transition-\[width\]/)
  assert.equal(sidebar.match(/data-sidebar-fixed-column="true"/g)?.length, 4)
  assert.match(sidebar, /className="w-72 shrink-0 space-y-1 px-3"/)
  assert.equal(sidebar.match(/collapsed \? 'w-10' : 'w-\[264px\]'/g)?.length, 2)
  assert.match(sidebar, /flex h-10 w-10 shrink-0 items-center justify-center/)
  assert.doesNotMatch(sidebar, /collapsed \? 'justify-center/)
  assert.doesNotMatch(sidebar, /PanelLeftOpen|PanelLeftClose|onToggleCollapsed/)
  assert.doesNotMatch(sidebar, /t\('app\.subtitle'\)/)
  assert.match(tauriConfig, /"decorations": false/)
  for (const permission of ['close', 'minimize', 'start-dragging', 'toggle-maximize']) {
    assert.match(desktopCapabilities, new RegExp(`core:window:allow-${permission}`))
  }
})

test('Notebook and Personalization are standalone while Sources stays RAG-only', () => {
  assert.match(app, /view === 'notebook'/)
  assert.match(app, /view === 'memory'/)
  assert.doesNotMatch(knowledge, /NotesPage|Search Sources and Notes/)
  assert.doesNotMatch(settings, /UserMemoryPage|LegacyMigrationPanel/)
  assert.doesNotMatch(memory, /LegacyMigrationPanel|\/api\/migration\/legacy/)
  assert.match(knowledgePage, /资料集/)
  assert.match(knowledgePage, /参考资料/)
  assert.doesNotMatch(knowledgePage, /知识库/)
})

test('Notebook keeps its IDE-like workspace instead of regressing to a flat note list', () => {
  assert.match(notebook, /function NotebookFileTree/)
  assert.match(notebook, /function NotebookRelationsPanel/)
  assert.match(notebook, /NOTEBOOK_TREE_ROW_HEIGHT/)
  assert.match(notebook, /openDesktopContextMenu/)
  assert.match(notebook, /\/api\/notebook\/folders/)
  assert.match(notebook, /resolveWikiLink/)
  assert.match(notebook, /onWikiLinkOpen/)
  assert.match(notebook, /backlinks/)
  assert.match(notebook, /局部关系图/)
  assert.match(notebook, /vaultMenuOpen/)
  assert.doesNotMatch(notebook, /window\.prompt/)
  assert.match(notebook, /aria-label=\{english \? 'New folder name' : '新目录名称'\}/)
  assert.match(notebook, /data-notebook-tree-row="true"/)
  assert.match(notebook, />\{node\.name\}<\/span>/)
  assert.doesNotMatch(notebook, /node\.name\.replace\(\/\\\.md\$\/i, ''\)/)
  assert.match(notebook, /mx-1 mb-1 flex h-7 w-auto/)
  assert.match(notebook, /ring-inset ring-blue-100/)
  assert.match(notebook, /Copy folder path|复制文件夹路径/)
  assert.match(notebook, /onContextMenu=\{openRootContextMenu\}/)
  assert.match(notebook, /className=\{compactButtonClassName\}[\s\S]*?onClick=\{\(\) => void createEntry\(\)\}/)
  assert.match(notebook, /className=\{compactButtonClassName\}[\s\S]*?onClick=\{\(\) => startCreateFolder\(\)\}/)
  assert.doesNotMatch(notebook, /Collapse Folder|折叠目录/)
  assert.match(notebook, /Delete Folder|删除目录/)
  assert.match(notebook, /Rename Folder|重命名目录/)
  assert.match(notebook, /Rename Note|重命名笔记/)
  assert.match(notebook, /onDoubleClick/)
  assert.match(notebook, /method: 'PATCH'/)
  assert.doesNotMatch(notebook, /aria-label=\{english \? 'Note title' : '笔记标题'\}/)
  assert.doesNotMatch(notebook, /aria-label=\{english \? 'Note path' : '笔记路径'\}/)
  assert.match(notebook, /method: 'DELETE'/)
  assert.match(notebookRoutes, /delete_empty_folder/)
  assert.match(notebookRoutes, /\.delete\(delete_folder\)/)
  assert.match(notebook, /function FolderDeleteDialog/)
  assert.match(notebook, /目录不是空目录/)
  assert.match(notebook, /仍要删除/)
  assert.match(notebook, /recursive=true/)
  assert.match(notebook, /\/api\/notebook\/folders\/restore/)
  assert.match(notebookRoutes, /trash_folder/)
  assert.match(notebookRoutes, /restore_trashed_folder/)
  assert.match(notebookRoutes, /rename_folder/)
  assert.match(notebookRoutes, /\.patch\(rename_folder\)/)
  assert.match(notebook, /<NotebookLiveEditor/)
  assert.match(notebook, /lazy\(\(\) => import\('\.\/NotebookLiveEditor'\)/)
  assert.match(notebookLiveEditor, /new Vditor/)
  assert.match(notebookLiveEditor, /mode: 'ir'/)
  assert.match(notebookLiveEditor, /toolbar: \[\]/)
  assert.match(notebookLiveEditor, /data-notebook-direct-editor="true"/)
  assert.match(notebookLiveEditor, /input: \(value\)/)
  assert.match(notebookLiveEditor, /if \(!disposed && ready\) acceptEditorValue\(value\)/)
  assert.match(notebookLiveEditor, /window\.setTimeout/)
  assert.doesNotMatch(notebookLiveEditor, /<textarea/)
  assert.doesNotMatch(notebookLiveEditor, /CrepeBuilder|@milkdown/)
  assert.doesNotMatch(notebook, /onStartEdit|onCancelEdit|Markdown 编辑器/)
  assert.match(desktopBehavior, /value\.startsWith\('#'\)/)
  assert.match(desktopBehavior, /anchor\.getAttribute\('href'\)/)
})

test('assistant setup is managed from Personalization instead of Settings', () => {
  assert.match(memory, /Assistant setup|助手设定/)
  assert.match(memory, /About me|关于我/)
  assert.match(memory, /assistantName/)
  assert.match(memory, /assistantInstructions/)
  assert.match(memory, /useState<'memory' \| 'assistant'>\('memory'\)/)
  assert.match(memory, /role="tablist"/)
  assert.match(memory, /id="memory"/)
  assert.match(memory, /id="assistant-profile"/)
  assert.match(memory, /id=\{`\$\{id\}-tab`\}/)
  assert.match(memory, /onSessionNavigate/)
  assert.match(memory, /留空则使用默认 Folumi 设定/)
  assert.match(memory, /自动保存，仅影响新对话/)
  assert.match(memory, /查看默认设定/)
  assert.match(memory, /customNameWithDefaultIdentity/)
  assert.doesNotMatch(settings, /Assistant setup|助手设定|assistantName|assistantInstructions/)
  assert.match(app, /onAssistantProfileChange/)
})

test('legacy data migration stays outside the active product boundary', () => {
  assert.doesNotMatch(backendMain, /migration_router|\/api\/migration\/legacy/)
  assert.doesNotMatch(backendRoutes, /pub mod migration/)
})

test('retired layered memory is presented as revisioned personal information', () => {
  const activeBackend = [backendMain, notebookRoutes, knowledgeRoutes, websocketRoutes].join('\n')
  assert.doesNotMatch(activeBackend, /MemoryEventCategory|record_event|memory_workflow|L1\/|L2\/|L3\//)
  assert.match(memory, /Personal information|个人信息/)
  assert.match(memory, /\/api\/memory\/items/)
  assert.match(memory, /\/api\/memory\/export\.json/)
  assert.match(memory, /reconfirm: true/)
  assert.match(memoryRoutes, /revision/)
  assert.match(memoryStore, /memory-v2|memory_items|superseded|memory_tombstones/)
  assert.doesNotMatch(memory, /file_revision|marker|L1\/|L2\/|L3\//)
  assert.match(app, /approval_request|approval_response/)
  assert.match(backendRoutes, /pub mod memory/)
})

test('past conversation reference is visible tool search without hidden pre-run injection', () => {
  assert.match(memory, /Reference past conversations|参考过往对话/)
  assert.match(memory, /需要时查找你以前聊过的内容/)
  assert.doesNotMatch(memory, /由 runtime 提供|Runtime powered/)
  assert.match(websocketRoutes, /source_id exactly `session_recall`/)
  assert.match(websocketRoutes, /tool trace and source link/)
  assert.doesNotMatch(websocketRoutes, /with_runtime_plugin|history_recall_plugin/)
})

test('assistant personal-information updates are proactive but user-controlled', () => {
  assert.match(memory, /允许助手自动补充/)
  assert.match(memory, /assistant_write_without_approval/)
  assert.match(websocketRoutes, /clearly durable and personally useful context/)
  assert.match(websocketRoutes, /Memory deletion still requires explicit user intent and separate approval/)
})

test('memory controls share one settings card and the search field has no overlapping icon', () => {
  const settingsIndex = memory.indexOf("english ? 'Personal context'")
  const historyIndex = memory.indexOf("english ? 'Reference past conversations'")
  const itemsIndex = memory.indexOf("english ? 'Personal information'")
  assert.ok(settingsIndex >= 0 && settingsIndex < historyIndex && historyIndex < itemsIndex)
  assert.doesNotMatch(memory, /<Search\b/)
})

test('temporary conversations are explicit and disable memory continuity', () => {
  assert.match(app, /临时对话/)
  assert.match(app, /temporary: temporaryConversation/)
  assert.match(websocketRoutes, /session_memory_features/)
  assert.match(websocketRoutes, /entry\.temporary/)
})

test('assistant header avoids duplicate source scope and keeps Temporary Chat compact', () => {
  assert.doesNotMatch(app, /资料范围|Conversation only/)
  assert.match(app, /peer-checked:bg-amber-500/)
  assert.doesNotMatch(app, /BudgetPanel|budgetSpent|budget_warning/)
  assert.doesNotMatch(settings, /Session budget|budgetLimitUsd/)
})

test('ordinary run completion clears transient progress without adding an internal Done message', () => {
  const doneHandler = app.match(/else if \(kind === 'done'\) \{([\s\S]*?)\} else if \(kind === 'history_sync'\)/)?.[1]
  assert.ok(doneHandler)
  assert.match(doneHandler, /dropTrailingTransientStatus/)
  assert.doesNotMatch(doneHandler, /pushStatus|context messages|history_len/)
})

test('retired Research mode is absent while normal Chat keeps source tools', () => {
  assert.doesNotMatch(composer, /openMenu === 'mode'/)
  assert.doesNotMatch(composer, /visibleModeOptions/)
  assert.doesNotMatch(composer, /cap\.research|capability === 'research'|ResearchReportMessage/)
  assert.doesNotMatch(productGuide, /Research|研究模式|调研 workflow/)
  assert.doesNotMatch(agentCapability, /Capability::Research|Research,/)
  assert.doesNotMatch(agentLibrary, /pub mod research|pub mod runtime_workflow/)
  assert.match(websocketRoutes, /with_web_search/)
})

test('onboarding teaches model, sources, and asking without legacy hierarchy', () => {
  assert.match(onboarding, /steps: \['准备模型', '加入资料', '开始提问'\]/)
  assert.doesNotMatch(onboarding, /onManageTutors|onOpenMemory|OnboardingModeGuide/)
  assert.doesNotMatch(onboarding, /RAG|向量|Agent|runtime|上下文/)
})

test('high-frequency interface copy uses short everyday language', () => {
  assert.match(memory, /在新对话中使用已保存的个人信息/)
  assert.match(memory, /自动记住你明确说过的重要信息/)
  assert.match(i18n, /'settings\.tabs\.llm': 'LLM'/)
  assert.match(i18n, /'settings\.tabs\.embedding': '嵌入模型'/)
  assert.match(i18n, /'settings\.tabs\.search': '联网搜索'/)
  assert.doesNotMatch(settings, /key: 'governance'|权限与数据|执行操作前先询问我|本地数据目录/)
  assert.doesNotMatch(i18n, /settings\.tabs\.governance|settings\.governance\.description/)
  assert.match(knowledgePage, />\s*添加文档\s*</)
  assert.match(knowledgePage, />\s*查找\s*</)
  assert.match(knowledgePage, />\s*重新整理\s*</)
  assert.match(knowledgePage, /请先在设置中配置“嵌入模型”/)
  assert.doesNotMatch(knowledgePage, /设置中完成“资料查找”/)
})

test('composer removes per-message note mentions', () => {
  assert.doesNotMatch(composer, /\/api\/notebook\/mentions|\/api\/space\/mentions|AtSign|NotebookMention/)
})

test('composer selectors share one polished dropdown surface', () => {
  assert.equal(composer.match(/<DropdownPanel/g)?.length, 2)
  assert.match(composer, /data-composer-dropdown="true"/)
  assert.match(composer, /rounded-2xl border border-gray-200\/90/)
  assert.match(composer, /title=\{t\('chat\.source\.menu\.title'\)\}/)
  assert.match(composer, /title=\{t\('chat\.model\.menu\.title'\)\}/)
  assert.match(composer, /selectedKnowledgeBaseIds\.includes\(item\.id\)/)
  assert.doesNotMatch(composer, /chat\.knowledge\.none/)
  assert.match(composer, /line-clamp-2/)
})

test('reasoning models expose an adjustable level and inline thinking surface', () => {
  assert.match(settingsSchema, /thinkingLevel: ThinkingLevel/)
  assert.match(settings, /思考强度/)
  assert.match(settings, /value="off">关闭/)
  assert.match(settings, /value="medium">中/)
  assert.match(settings, /value="xhigh">极高/)
  assert.match(composer, /ThinkingDisclosure/)
  assert.match(composer, /openMenu === 'thinking'/)
  assert.match(composer, /onThinkingLevelChange\(option\.value\)/)
  assert.match(composer, /chat\.thinking\.session/)
  assert.match(composer, /思考中/)
  assert.match(composer, /思考过程/)
  assert.match(websocket, /type: 'thinking_content'/)
})

test('Notebook supports named vault switching instead of a permanent refresh button', () => {
  assert.match(notebook, /vaults\.find\(\(vault\) => vault\.active\)\?\.name/)
  assert.match(notebook, /\/api\/notebook\/vaults\//)
  assert.match(notebook, /管理笔记库/)
  assert.match(notebook, /border border-blue-300 bg-blue-50/)
  assert.match(notebook, /添加一个笔记库/)
  assert.doesNotMatch(notebook, /RefreshCw|刷新笔记/)
  assert.match(settings, /添加笔记库/)
  assert.match(settings, /确认移除/)
  assert.doesNotMatch(settings, /notebookVaults\.length <= 1/)
  assert.doesNotMatch(settings, /导入笔记|导出笔记|Obsidian Vault|\/api\/notebook\/import|\/api\/notebook\/export/)
  const notebookRouter = notebookRoutes.slice(notebookRoutes.indexOf('pub fn notebook_router'), notebookRoutes.indexOf('fn error_response'))
  assert.doesNotMatch(notebookRouter, /\/api\/notebook\/(?:import|export)|export\.md/)
  assert.match(composer, /notebookVaults\.map/)
  assert.match(app, /notebook_vault_id/)
})
